<h4>Impute the missing value by Using MICE

In [3]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.linear_model import LinearRegression

In [12]:
#Custom dataset
df=pd.DataFrame(
    {
        'Age':[25,30,32,40,np.nan],
        'Experience':[np.nan,5,6,7,9],
        'Salary':[40,47,np.nan,60,68],
        'Personal Loan':[1,0,1,1,0]
    }
)

In [13]:
df

    Age  Experience  Salary  Personal Loan
0  25.0         NaN    40.0              1
1  30.0         5.0    47.0              0
2  32.0         6.0     NaN              1
3  40.0         7.0    60.0              1
4   NaN         9.0    68.0              0

In [14]:
x=df.drop(columns=['Personal Loan'])
y=df['Personal Loan']

<h4>On the base of correlation decide the estimate model like linear regression etc

In [15]:
x.corr()

                 Age  Experience    Salary
Age         1.000000    0.944911  0.999827
Experience  0.944911    1.000000  0.990684
Salary      0.999827    0.990684  1.000000

In [16]:
model=LinearRegression()

In [17]:
mice=IterativeImputer(estimator=model,max_iter=30,imputation_order='roman')

In [21]:
r=mice.fit_transform(x)

In [22]:
r

array([[25.        ,  3.51932571, 40.        ],
       [30.        ,  5.        , 47.        ],
       [32.        ,  6.        , 50.21214346],
       [40.        ,  7.        , 60.        ],
       [45.4346887 ,  9.        , 68.        ]])