In [2]:
import pandas as pd
import numpy as np

In [37]:
df=pd.read_csv('Mobile_datase.csv')

In [38]:
df1=df.copy()

In [40]:
df1[df1['Phone_price'].isna()]

,Unnamed: 0,Phone_name,Rating,Reviews,Phone_price,Discounted_price,Phone_image
12,12,Xiaomi Poco C75,4.9,182.0,NaN,"Rs 36,999",https://images.priceoye.pk/xiaomi-poco-c75-pak...
16,16,Memobile I Smart Pro,NaN,NaN,NaN,"Rs 3,349",https://images.priceoye.pk/memobile-i-smart-pr...
28,28,GFive Note 25,5.0,1.0,NaN,"Rs 20,499",https://images.priceoye.pk/gfive-pakistan-pric...
35,35,Itel A100,5.0,2.0,NaN,"Rs 24,499",https://images.priceoye.pk/itel-a100-pakistan-...
52,52,OPPO Reno 15,5.0,1.0,NaN,"Rs 159,999",https://images.priceoye.pk/oppo-reno15-pakista...
...,...,...,...,...,...,...,...
681,681,E-tachi B13 Vip,NaN,NaN,NaN,"Rs 2,899",https://static.priceoye.pk/images/out-of-stock...
682,682,E-tachi I pro 15,NaN,NaN,NaN,"Rs 5,200",https://static.priceoye.pk/images/out-of-stock...
683,683,Club Mobile Magic 3,NaN,NaN,NaN,"Rs 4,599",https://static.priceoye.pk/images/out-of-stock...
684,684,E-tachi Power 1000,NaN,NaN,NaN,"Rs 4,450",https://static.priceoye.pk/images/out-of-stock...
685,685,E-tachi Smart Plus,NaN,NaN,NaN,"Rs 3,499",https://static.priceoye.pk/images/out-of-stock...

In [41]:
df1.drop('Unnamed: 0',axis=1,inplace=True)

In [42]:
df1['Phone_price']=df1['Phone_price'].str.replace('Rs ','').str.replace(',','')

In [43]:
df1['Phone_price']=df1['Phone_price'].astype('float')

In [44]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 686 entries, 0 to 685
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Phone_name        686 non-null    str
 1   Rating            406 non-null    float64
 2   Reviews           406 non-null    float64
 3   Phone_price       456 non-null    float64
 4   Discounted_price  686 non-null    str
 5   Phone_image       686 non-null    str
dtypes: float64(3), str(3)
memory usage: 32.3 KB

In [45]:
df1['Discounted_price']=df1['Discounted_price'].str.replace('Rs ','').str.replace(',','')

In [46]:
df1['Discounted_price']=df1['Discounted_price'].astype('float')

In [47]:
df1.reset_index(inplace=True)

In [67]:
temp_df=df1[df1['Phone_price'].isna()]

In [78]:
temp_df['Phone_price']=temp_df['Discounted_price'].values

In [94]:
x_index=temp_df.index
x_values=temp_df.iloc[:,4:6].values

In [97]:
df1.iloc[x_index,4:6]=x_values

In [102]:
df1.sample(5)

,index,Phone_name,Rating,Reviews,Phone_price,Discounted_price,Phone_image
292,292,Club Mobile Power 666,NaN,NaN,3999.0,3049.0,https://images.priceoye.pk/clubmobile-power-66...
225,225,Honor X9c,5.0,8.0,99999.0,93999.0,https://images.priceoye.pk/honor-x9c-pakistan-...
306,306,Samsung Galaxy S24,5.0,14.0,289999.0,209999.0,https://images.priceoye.pk/samsung-galaxy-s24-...
132,132,Itel S24,4.8,237.0,33999.0,33999.0,https://images.priceoye.pk/itel-s24-pakistan-p...
70,70,E-Tachi Magic E4,NaN,NaN,3849.0,3849.0,https://images.priceoye.pk/e-tachi-magic-e4-pa...

In [105]:
df1.drop('Discounted_price',axis=1,inplace=True)

In [106]:
df1.head()

,index,Phone_name,Rating,Reviews,Phone_price,Phone_image
0,0,Tecno Camon 40 Pro,4.9,41.0,69999.0,https://images.priceoye.pk/tecno-camon-40-pro-...
1,1,Samsung Galaxy A17,4.8,47.0,59500.0,https://images.priceoye.pk/samsung-galaxy-a17-...
2,2,Tecno Spark Go 2,4.9,28.0,26999.0,https://images.priceoye.pk/tecno-spark-go-2-pa...
3,3,Samsung Galaxy A56 5G,5.0,68.0,137999.0,https://images.priceoye.pk/samsung-galaxy-a56-...
4,4,Infinix Hot 60 Pro Plus,5.0,25.0,61999.0,https://images.priceoye.pk/infinix-hot-60-pro-...

In [113]:
df1['Phone_price']=df1['Phone_price'].astype('int')

In [126]:
brand_name=df1['Phone_name'].str.strip().str.split(' ').str.get(0)

In [127]:
brand_name

0        Tecno
1      Samsung
2        Tecno
3      Samsung
4      Infinix
        ...
681    E-tachi
682    E-tachi
683       Club
684    E-tachi
685    E-tachi
Name: Phone_name, Length: 686, dtype: object

In [149]:
model_name=df1['Phone_name'].str.strip().str.split().str[1:].str.join(' ')

In [150]:
model_name

0         Camon 40 Pro
1           Galaxy A17
2           Spark Go 2
3        Galaxy A56 5G
4      Hot 60 Pro Plus
            ...
681            B13 Vip
682           I pro 15
683     Mobile Magic 3
684         Power 1000
685         Smart Plus
Name: Phone_name, Length: 686, dtype: object

In [ ]:
df1.insert(1,'brand_name',brand_name)

In [153]:
df1['model_name']=model_name.values

In [157]:
df1.drop('Phone_name',axis=1,inplace=True)

In [158]:
df1.head()

,index,brand_name,model_name,Rating,Reviews,Phone_price,Phone_image
0,0,Tecno,Camon 40 Pro,4.9,41.0,69999,https://images.priceoye.pk/tecno-camon-40-pro-...
1,1,Samsung,Galaxy A17,4.8,47.0,59500,https://images.priceoye.pk/samsung-galaxy-a17-...
2,2,Tecno,Spark Go 2,4.9,28.0,26999,https://images.priceoye.pk/tecno-spark-go-2-pa...
3,3,Samsung,Galaxy A56 5G,5.0,68.0,137999,https://images.priceoye.pk/samsung-galaxy-a56-...
4,4,Infinix,Hot 60 Pro Plus,5.0,25.0,61999,https://images.priceoye.pk/infinix-hot-60-pro-...