<h4>By using custom logic perform naive bayes

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('playtennis.csv')

In [3]:
df.head()

    Outlook Temperature Humidity    Wind PlayTennis
0     Sunny         Hot     High    Weak         No
1  Overcast        Mild   Normal  Strong         No
2  Overcast        Cool   Normal     NaN        Yes
3      Rain        Mild     High  Strong         No
4      Rain         Hot   Normal    Weak        Yes

In [51]:
y_n=df['PlayTennis'].value_counts(normalize=True)

In [52]:
y_n

PlayTennis
Yes    0.6
No     0.4
Name: proportion, dtype: float64

In [20]:
pd.crosstab(df['Outlook'],df['PlayTennis'],normalize='columns')

PlayTennis    No   Yes
Outlook
Overcast    0.05  0.45
Rain        0.55  0.25
Sunny       0.40  0.30

In [19]:
#To calculate conditional probability use columns
pd.crosstab(df['Outlook'],df['PlayTennis'],normalize='columns').stack()

Outlook   PlayTennis
Overcast  No            0.05
          Yes           0.45
Rain      No            0.55
          Yes           0.25
Sunny     No            0.40
          Yes           0.30
dtype: float64

In [ ]:
df.columns

Index(['Outlook', 'Temperature', 'Humidity', 'Wind', 'PlayTennis'], dtype='str')

In [16]:
pro={}
for i in ['Outlook', 'Temperature', 'Humidity', 'Wind']:
    pro.update(pd.crosstab(df[i],df['PlayTennis'],normalize='columns').stack().to_dict())

In [17]:
pro

{('Overcast', 'No'): 0.05,
 ('Overcast', 'Yes'): 0.45,
 ('Rain', 'No'): 0.55,
 ('Rain', 'Yes'): 0.25,
 ('Sunny', 'No'): 0.4,
 ('Sunny', 'Yes'): 0.3,
 ('Cool', 'No'): 0.4125,
 ('Cool', 'Yes'): 0.275,
 ('Hot', 'No'): 0.3125,
 ('Hot', 'Yes'): 0.3,
 ('Mild', 'No'): 0.275,
 ('Mild', 'Yes'): 0.425,
 ('High', 'No'): 0.7435897435897436,
 ('High', 'Yes'): 0.3008849557522124,
 ('Normal', 'No'): 0.2564102564102564,
 ('Normal', 'Yes'): 0.6991150442477876,
 ('Strong', 'No'): 0.5256410256410257,
 ('Strong', 'Yes'): 0.3392857142857143,
 ('Weak', 'No'): 0.47435897435897434,
 ('Weak', 'Yes'): 0.6607142857142857}

In [56]:
pro_y,pro_n=y_n.values

In [57]:
pro_y

np.float64(0.6)

In [59]:
df.head(1)

  Outlook Temperature Humidity  Wind PlayTennis
0   Sunny         Hot     High  Weak         No

In [78]:
def play_status(outlook,temperature,humidity,wind,pro,pro_y,pro_n):
    yes=pro_y*(pro[outlook,'Yes']*pro[temperature,'Yes']*pro[humidity,'Yes']*pro[wind,'Yes'])
    no=pro_n*(pro[outlook,'No']*pro[temperature,'No']*pro[humidity,'No']*pro[wind,'No'])
    if yes>no:
        print('Yes')
    else:
        print('No')

<h4>By changing loc value we can see the result according to the dataset

In [100]:
loc=12

In [101]:
data=df.iloc[loc].to_list()[:-1]

In [102]:
data

['Overcast', 'Hot', 'Normal', 'Strong']

In [103]:
play_status(data[0],data[1],data[2],data[3],pro,pro_y,pro_n)
print(df['PlayTennis'][loc])

Yes
Yes

In [104]:
df.head()

    Outlook Temperature Humidity    Wind PlayTennis
0     Sunny         Hot     High    Weak         No
1  Overcast        Mild   Normal  Strong         No
2  Overcast        Cool   Normal     NaN        Yes
3      Rain        Mild     High  Strong         No
4      Rain         Hot   Normal    Weak        Yes